### ISSUE TITLE
plugin does not regenerate .cfg one deleted from csg\sourcemod

### ISSUE THREAD

**Issue by flsflameboy1** [totles/z4lab-hub#7]
changing the prefix withing the z4lab_hub.cfg does not change the prefix given

**Comment by 13ace37** [comment]
The config is just an autogenerated file from sourcemod and it sets the plugins cvars. 
So I don’t really get your problem here. If you delete the file sourcemod should regenerate one. If not, reinstall the plugin or create one yourself.
The config file has nothing to do with the plugin. That's more like a sourcemod problem.
